spring:
  cloud:
    refresh:
      enabled: false
    loadbalancer:
      eager-load:
        clients: subscriptions-svc, users-svc, whatsapp-svc
  application:
    name: remind-pack-resi-svc
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}